# Site settings
title: Giovanni's web page
author:
  name: Giovanni Sold√†
  email: giovanni dot a dot solda at gmail.com
  url: "https://orcid.org/0000-0003-4903-3623"
  
exclude:
 - README.md
 - about.md

# Build settings
remote_theme: jekyll/minima
